import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.company': 'Company',
    'nav.clients': 'Clients',
    'nav.invoices': 'Invoices',
    'nav.automation': 'Automation',
    'nav.payment': 'Payment',
    'nav.payments': 'Payments',
    'nav.integrations': 'Integrations',
    'nav.settings': 'Settings',
    
    // Payment Page
    'payment.title': 'Payment',
    'payment.subtitle': 'Manage your wallet and transactions',
    'payment.walletOverview': 'Wallet Overview',
    'payment.availableBalance': 'Available Balance',
    'payment.accountNumber': 'Account Number',
    'payment.quickAction': 'Quick Action',
    'payment.send': 'Send',
    'payment.receive': 'Receive',
    'payment.transfer': 'Transfer',
    'payment.addFunds': 'Add Funds',
    'payment.quickTransfer': 'Quick Transfer',
    'payment.transactionsList': 'Transactions List',
    'payment.searchTransactions': 'Search transactions...',
    'payment.namesBusiness': 'Name/Business',
    'payment.dateTime': 'Date/Time',
    'payment.method': 'Method',
    'payment.type': 'Type',
    'payment.amount': 'Amount',
    'payment.action': 'Action',
    'payment.sendMoney': 'Send Money',
    'payment.recipient': 'Recipient',
    'payment.recipientPlaceholder': 'Enter recipient name or email',
    'payment.amountPlaceholder': '0.00',
    'payment.export': 'Export',
    'payment.filters': 'Filters',
    'payment.all': 'All',
    'payment.withdraw': 'Withdraw',
    'payment.debitCard': 'Debit Card',
    'payment.creditCard': 'Credit Card',
    'payment.completed': 'Completed',
    'payment.receiveFunds': 'Receive funds feature coming soon',
    'payment.insufficientBalance': 'Insufficient balance',
    'payment.fillAllFields': 'Please fill in all fields',
    'payment.enterAmount': 'Please enter an amount',
    'payment.sentSuccess': 'sent successfully',
    'payment.addedSuccess': 'added to your wallet',
    
    // Clients Page
    'clients.title': 'Clients',
    'clients.subtitle': 'Manage your clients and contacts',
    'clients.add': 'Add Client',
    'clients.noClients': 'No clients found',
    'clients.getStarted': 'Get started by adding your first client.',
    'clients.name': 'Name',
    'clients.email': 'Email',
    'clients.company': 'Company',
    'clients.phone': 'Phone',
    'clients.status': 'Status',
    'clients.actions': 'Actions',
    'clients.edit': 'Edit',
    'clients.view': 'View',
    'clients.delete': 'Delete',
    
    // Invoices Page
    'invoices.title': 'Invoices',
    'invoices.subtitle': 'Manage your invoices and billing',
    'invoices.create': 'Create Invoice',
    'invoices.invoice': 'Invoice',
    'invoices.client': 'Client',
    'invoices.issueDate': 'Issue Date',
    'invoices.dueDate': 'Due Date',
    'invoices.amount': 'Amount',
    'invoices.status': 'Status',
    'invoices.payment': 'Payment',
    'invoices.actions': 'Actions',
    'invoices.preview': 'Preview',
    'invoices.edit': 'Edit',
    'invoices.delete': 'Delete',
    'invoices.markPaid': 'Mark as Paid',
    'invoices.markUnpaid': 'Mark as Unpaid',
    'invoices.downloadPdf': 'Download PDF',
    'invoices.sendEmail': 'Send Email',
    'invoices.noInvoices': 'No invoices found',
    'invoices.getStartedInvoices': 'Get started by creating your first invoice.',
    
    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your application preferences',
    'settings.general': 'General',
    'settings.invoicing': 'Invoicing',
    'settings.notifications': 'Notifications',
    'settings.security': 'Security',
    'settings.save': 'Save Settings',
    'settings.companyName': 'Company Name',
    'settings.defaultCurrency': 'Default Currency',
    'settings.defaultLanguage': 'Default Language',
    'settings.timeZone': 'Time Zone',
    'settings.dateFormat': 'Date Format',
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.actions': 'Actions',
    'common.search': 'Search...',
    'common.export': 'Export',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    
    // Status
    'status.draft': 'Draft',
    'status.sent': 'Sent',
    'status.paid': 'Paid',
    'status.unpaid': 'Unpaid',
    'status.partial': 'Partial',
    'status.overdue': 'Overdue',
    'status.cancelled': 'Cancelled',
    'status.pending': 'Pending',
    'status.viewed': 'Viewed'
  },
  es: {
    // Navigation
    'nav.dashboard': 'Panel',
    'nav.company': 'Empresa',
    'nav.clients': 'Clientes',
    'nav.invoices': 'Facturas',
    'nav.automation': 'Automatización',
    'nav.payment': 'Pago',
    'nav.payments': 'Pagos',
    'nav.integrations': 'Integraciones',
    'nav.settings': 'Configuración',
    
    // Payment Page
    'payment.title': 'Pago',
    'payment.subtitle': 'Gestiona tu billetera y transacciones',
    'payment.walletOverview': 'Resumen de Billetera',
    'payment.availableBalance': 'Saldo Disponible',
    'payment.accountNumber': 'Número de Cuenta',
    'payment.quickAction': 'Acción Rápida',
    'payment.send': 'Enviar',
    'payment.receive': 'Recibir',
    'payment.transfer': 'Transferir',
    'payment.addFunds': 'Agregar Fondos',
    'payment.quickTransfer': 'Transferencia Rápida',
    'payment.transactionsList': 'Lista de Transacciones',
    'payment.searchTransactions': 'Buscar transacciones...',
    'payment.namesBusiness': 'Nombre/Negocio',
    'payment.dateTime': 'Fecha/Hora',
    'payment.method': 'Método',
    'payment.type': 'Tipo',
    'payment.amount': 'Cantidad',
    'payment.action': 'Acción',
    'payment.sendMoney': 'Enviar Dinero',
    'payment.recipient': 'Destinatario',
    'payment.recipientPlaceholder': 'Ingrese nombre o email del destinatario',
    'payment.amountPlaceholder': '0.00',
    'payment.export': 'Exportar',
    'payment.filters': 'Filtros',
    'payment.all': 'Todos',
    'payment.withdraw': 'Retirar',
    'payment.debitCard': 'Tarjeta de Débito',
    'payment.creditCard': 'Tarjeta de Crédito',
    'payment.completed': 'Completado',
    'payment.receiveFunds': 'Función de recibir fondos próximamente',
    'payment.insufficientBalance': 'Saldo insuficiente',
    'payment.fillAllFields': 'Por favor complete todos los campos',
    'payment.enterAmount': 'Por favor ingrese una cantidad',
    'payment.sentSuccess': 'enviado exitosamente',
    'payment.addedSuccess': 'agregado a tu billetera',
    
    // Clients Page
    'clients.title': 'Clientes',
    'clients.subtitle': 'Gestiona tus clientes y contactos',
    'clients.add': 'Añadir Cliente',
    'clients.noClients': 'No se encontraron clientes',
    'clients.getStarted': 'Comienza añadiendo tu primer cliente.',
    'clients.name': 'Nombre',
    'clients.email': 'Email',
    'clients.company': 'Empresa',
    'clients.phone': 'Teléfono',
    'clients.status': 'Estado',
    'clients.actions': 'Acciones',
    'clients.edit': 'Editar',
    'clients.view': 'Ver',
    'clients.delete': 'Eliminar',
    
    // Invoices Page
    'invoices.title': 'Facturas',
    'invoices.subtitle': 'Gestiona tus facturas y facturación',
    'invoices.create': 'Crear Factura',
    'invoices.invoice': 'Factura',
    'invoices.client': 'Cliente',
    'invoices.issueDate': 'Fecha de Emisión',
    'invoices.dueDate': 'Fecha de Vencimiento',
    'invoices.amount': 'Cantidad',
    'invoices.status': 'Estado',
    'invoices.payment': 'Pago',
    'invoices.actions': 'Acciones',
    'invoices.preview': 'Vista Previa',
    'invoices.edit': 'Editar',
    'invoices.delete': 'Eliminar',
    'invoices.markPaid': 'Marcar como Pagado',
    'invoices.markUnpaid': 'Marcar como No Pagado',
    'invoices.downloadPdf': 'Descargar PDF',
    'invoices.sendEmail': 'Enviar Email',
    'invoices.noInvoices': 'No se encontraron facturas',
    'invoices.getStartedInvoices': 'Comienza creando tu primera factura.',
    
    // Settings
    'settings.title': 'Configuración',
    'settings.subtitle': 'Gestiona las preferencias de tu aplicación',
    'settings.general': 'General',
    'settings.invoicing': 'Facturación',
    'settings.notifications': 'Notificaciones',
    'settings.security': 'Seguridad',
    'settings.save': 'Guardar Configuración',
    'settings.companyName': 'Nombre de la Empresa',
    'settings.defaultCurrency': 'Moneda Predeterminada',
    'settings.defaultLanguage': 'Idioma Predeterminado',
    'settings.timeZone': 'Zona Horaria',
    'settings.dateFormat': 'Formato de Fecha',
    
    // Common
    'common.loading': 'Cargando...',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.view': 'Ver',
    'common.actions': 'Acciones',
    'common.search': 'Buscar...',
    'common.export': 'Exportar',
    'common.filter': 'Filtrar',
    'common.all': 'Todos',
    'common.active': 'Activo',
    'common.inactive': 'Inactivo',
    
    // Status
    'status.draft': 'Borrador',
    'status.sent': 'Enviado',
    'status.paid': 'Pagado',
    'status.unpaid': 'No Pagado',
    'status.partial': 'Parcial',
    'status.overdue': 'Vencido',
    'status.cancelled': 'Cancelado',
    'status.pending': 'Pendiente',
    'status.viewed': 'Visto'
  },
  fr: {
    // Navigation
    'nav.dashboard': 'Tableau de Bord',
    'nav.company': 'Entreprise',
    'nav.clients': 'Clients',
    'nav.invoices': 'Factures',
    'nav.automation': 'Automatisation',
    'nav.payment': 'Paiement',
    'nav.payments': 'Paiements',
    'nav.integrations': 'Intégrations',
    'nav.settings': 'Paramètres',
    
    // Payment Page
    'payment.title': 'Paiement',
    'payment.subtitle': 'Gérez votre portefeuille et transactions',
    'payment.walletOverview': 'Aperçu du Portefeuille',
    'payment.availableBalance': 'Solde Disponible',
    'payment.accountNumber': 'Numéro de Compte',
    'payment.quickAction': 'Action Rapide',
    'payment.send': 'Envoyer',
    'payment.receive': 'Recevoir',
    'payment.transfer': 'Transférer',
    'payment.addFunds': 'Ajouter des Fonds',
    'payment.quickTransfer': 'Transfert Rapide',
    'payment.transactionsList': 'Liste des Transactions',
    'payment.searchTransactions': 'Rechercher des transactions...',
    'payment.namesBusiness': 'Nom/Entreprise',
    'payment.dateTime': 'Date/Heure',
    'payment.method': 'Méthode',
    'payment.type': 'Type',
    'payment.amount': 'Montant',
    'payment.action': 'Action',
    'payment.sendMoney': 'Envoyer de l\'Argent',
    'payment.recipient': 'Destinataire',
    'payment.recipientPlaceholder': 'Entrez le nom ou email du destinataire',
    'payment.amountPlaceholder': '0.00',
    'payment.export': 'Exporter',
    'payment.filters': 'Filtres',
    'payment.all': 'Tous',
    'payment.withdraw': 'Retirer',
    'payment.debitCard': 'Carte de Débit',
    'payment.creditCard': 'Carte de Crédit',
    'payment.completed': 'Terminé',
    'payment.receiveFunds': 'Fonction de réception de fonds bientôt disponible',
    'payment.insufficientBalance': 'Solde insuffisant',
    'payment.fillAllFields': 'Veuillez remplir tous les champs',
    'payment.enterAmount': 'Veuillez entrer un montant',
    'payment.sentSuccess': 'envoyé avec succès',
    'payment.addedSuccess': 'ajouté à votre portefeuille',
    
    // Clients Page
    'clients.title': 'Clients',
    'clients.subtitle': 'Gérez vos clients et contacts',
    'clients.add': 'Ajouter un Client',
    'clients.noClients': 'Aucun client trouvé',
    'clients.getStarted': 'Commencez par ajouter votre premier client.',
    'clients.name': 'Nom',
    'clients.email': 'Email',
    'clients.company': 'Entreprise',
    'clients.phone': 'Téléphone',
    'clients.status': 'Statut',
    'clients.actions': 'Actions',
    'clients.edit': 'Modifier',
    'clients.view': 'Voir',
    'clients.delete': 'Supprimer',
    
    // Common
    'common.loading': 'Chargement...',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.view': 'Voir',
    'common.actions': 'Actions',
    'common.search': 'Rechercher...',
    'common.export': 'Exporter',
    'common.filter': 'Filtrer',
    'common.all': 'Tous',
    'common.active': 'Actif',
    'common.inactive': 'Inactif'
  },
  ar: {
    // Navigation
    'nav.dashboard': 'لوحة القيادة',
    'nav.company': 'الشركة',
    'nav.clients': 'العملاء',
    'nav.invoices': 'الفواتير',
    'nav.automation': 'الأتمتة',
    'nav.payment': 'الدفع',
    'nav.payments': 'المدفوعات',
    'nav.integrations': 'التكاملات',
    'nav.settings': 'الإعدادات',
    
    // Payment Page
    'payment.title': 'الدفع',
    'payment.subtitle': 'إدارة محفظتك والمعاملات',
    'payment.walletOverview': 'نظرة عامة على المحفظة',
    'payment.availableBalance': 'الرصيد المتاح',
    'payment.accountNumber': 'رقم الحساب',
    'payment.quickAction': 'إجراء سريع',
    'payment.send': 'إرسال',
    'payment.receive': 'استقبال',
    'payment.transfer': 'تحويل',
    'payment.addFunds': 'إضافة أموال',
    'payment.quickTransfer': 'تحويل سريع',
    'payment.transactionsList': 'قائمة المعاملات',
    'payment.searchTransactions': 'البحث في المعاملات...',
    'payment.namesBusiness': 'الاسم/الشركة',
    'payment.dateTime': 'التاريخ/الوقت',
    'payment.method': 'الطريقة',
    'payment.type': 'النوع',
    'payment.amount': 'المبلغ',
    'payment.action': 'الإجراء',
    'payment.sendMoney': 'إرسال أموال',
    'payment.recipient': 'المستقبل',
    'payment.recipientPlaceholder': 'أدخل اسم أو بريد إلكتروني للمستقبل',
    'payment.amountPlaceholder': '0.00',
    'payment.export': 'تصدير',
    'payment.filters': 'المرشحات',
    'payment.all': 'الكل',
    'payment.withdraw': 'سحب',
    'payment.debitCard': 'بطاقة مدين',
    'payment.creditCard': 'بطاقة ائتمان',
    'payment.completed': 'مكتمل',
    'payment.receiveFunds': 'ميزة استقبال الأموال قريباً',
    'payment.insufficientBalance': 'رصيد غير كافٍ',
    'payment.fillAllFields': 'يرجى ملء جميع الحقول',
    'payment.enterAmount': 'يرجى إدخال مبلغ',
    'payment.sentSuccess': 'تم الإرسال بنجاح',
    'payment.addedSuccess': 'تم إضافته إلى محفظتك',
    
    // Clients Page
    'clients.title': 'العملاء',
    'clients.subtitle': 'إدارة عملائك وجهات الاتصال',
    'clients.add': 'إضافة عميل',
    'clients.noClients': 'لم يتم العثور على عملاء',
    'clients.getStarted': 'ابدأ بإضافة أول عميل لك.',
    'clients.name': 'الاسم',
    'clients.email': 'البريد الإلكتروني',
    'clients.company': 'الشركة',
    'clients.phone': 'الهاتف',
    'clients.status': 'الحالة',
    'clients.actions': 'الإجراءات',
    'clients.edit': 'تعديل',
    'clients.view': 'عرض',
    'clients.delete': 'حذف',
    
    // Invoices Page
    'invoices.title': 'الفواتير',
    'invoices.subtitle': 'إدارة فواتيرك والفوترة',
    'invoices.create': 'إنشاء فاتورة',
    'invoices.invoice': 'فاتورة',
    'invoices.client': 'العميل',
    'invoices.issueDate': 'تاريخ الإصدار',
    'invoices.dueDate': 'تاريخ الاستحقاق',
    'invoices.amount': 'المبلغ',
    'invoices.status': 'الحالة',
    'invoices.payment': 'الدفع',
    'invoices.actions': 'الإجراءات',
    'invoices.preview': 'معاينة',
    'invoices.edit': 'تعديل',
    'invoices.delete': 'حذف',
    'invoices.markPaid': 'تعليم كمدفوع',
    'invoices.markUnpaid': 'تعليم كغير مدفوع',
    'invoices.downloadPdf': 'تحميل PDF',
    'invoices.sendEmail': 'إرسال بريد إلكتروني',
    'invoices.noInvoices': 'لم يتم العثور على فواتير',
    'invoices.getStartedInvoices': 'ابدأ بإنشاء أول فاتورة لك.',
    
    // Settings
    'settings.title': 'الإعدادات',
    'settings.subtitle': 'إدارة تفضيلات التطبيق',
    'settings.general': 'عام',
    'settings.invoicing': 'الفوترة',
    'settings.notifications': 'الإشعارات',
    'settings.security': 'الأمان',
    'settings.save': 'حفظ الإعدادات',
    'settings.companyName': 'اسم الشركة',
    'settings.defaultCurrency': 'العملة الافتراضية',
    'settings.defaultLanguage': 'اللغة الافتراضية',
    'settings.timeZone': 'المنطقة الزمنية',
    'settings.dateFormat': 'تنسيق التاريخ',
    
    // Common
    'common.loading': 'جاري التحميل...',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.view': 'عرض',
    'common.actions': 'الإجراءات',
    'common.search': 'بحث...',
    'common.export': 'تصدير',
    'common.filter': 'تصفية',
    'common.all': 'الكل',
    'common.active': 'نشط',
    'common.inactive': 'غير نشط',
    
    // Status
    'status.draft': 'مسودة',
    'status.sent': 'مُرسل',
    'status.paid': 'مدفوع',
    'status.unpaid': 'غير مدفوع',
    'status.partial': 'جزئي',
    'status.overdue': 'متأخر',
    'status.cancelled': 'ملغى',
    'status.pending': 'في الانتظار',
    'status.viewed': 'تمت المشاهدة'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    // Set document direction based on language
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    const langTranslations = translations[language as keyof typeof translations];
    return langTranslations?.[key as keyof typeof langTranslations] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};